Reduce amount of data used during discovery device to speed up the task
netascode/ansible-dc-vxlan pull request #185
Opened 2024-09-06 11:50 UTC by ccoueffe

Context: Testing on fabric having :
- 140 Leaves
- 1000 Vlans

Updating API to get Policies and filter with template equal to host_11_1 outside the loop in the task "Build Payload for NDFC Switch Hostname Policy Update"

This reduce the amount of data and improve time in the loop.

Shrink the data used on the task "Get Hostname for {{ item }} from Data Model" in the build_hostname_policy_payload to limit the data with only switches.

2024-09-06 13:19 UTC, juburnet commented
According to Charly, with this many Leaves and Vlans the current code fails deployment.  This fix is required to allow deployment successful

2024-09-06 13:38 UTC, mtarking requested changes

2024-09-06 13:38 UTC, mtarking commented on roles/dtc/create/tasks/devices_discovery.yml
> +    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/policies/pagination?filter=templateName==host_11_1&fabricName={{ MD.vxlan.global.name }}"
We cannot use this API as it's an internal-only API to NDFC and not publicly documented. It has potential to change without notice nor tracking thus not a good development practice to use. @dsx1123 @mikewiebe

2024-09-19 23:58 UTC, mtarking commented
Resolved by #190

2024-09-19 23:58 UTC, closed without merging