Update ndfc_policy.j2
netascode/ansible-dc-vxlan pull request #214
Opened 2024-10-31 10:49 UTC by mthurstocisco

Will now correctly handle other policies other than freeform that have a conf field (example we used is bgp_peer_template)

## Related Issue(s)

## Related Collection Role

* [ ] cisco.nac_dc_vxlan.validate
* [ ] cisco.nac_dc_vxlan.dtc.create
* [ ] cisco.nac_dc_vxlan.dtc.deploy
* [ ] cisco.nac_dc_vxlan.dtc.remove
* [ ] other

## Related Data Model Element

* [ ] vxlan.global
* [ ] vxlan.topology
* [ ] vxlan.underlay
* [ ] vxlan.overlay_services
* [ ] vxlan.overlay_extensions
* [ ] vxlan.policy
* [ ] defaults.vxlan
* [ ] other

## Proposed Changes

## Test Notes

## Cisco NDFC Version

## Checklist

* [ ] Latest commit is rebased from develop with merge conflicts resolved
* [ ] New or updates to documentation has been made accordingly
* [ ] Assigned the proper reviewers

2024-10-31 13:52 UTC, mikewiebe reviewed
LGTM, @mtarking can you take a look also?

2024-10-31 14:52 UTC, mtarking requested changes

2024-10-31 14:52 UTC, mtarking commented on roles/dtc/common/templates/ndfc_policy.j2
> +{% if key == 'CONF' and policy_match.template_name == 'switch_freeform' %}
We need to pickup the default value as a check here as well I think

2024-11-01 16:16 UTC, mthurstocisco commented
@mtarking updated based on the conversation we had.

2024-11-01 17:13 UTC, merged